//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hote
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hote()
        {
            this.Taocan = new HashSet<Taocan>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string addr { get; set; }
        public int type { get; set; }
        public decimal Price { get; set; }
        public string rongliang { get; set; }
        public string img { get; set; }
    
        public virtual type_Hote type_Hote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Taocan> Taocan { get; set; }
    }
}
