//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeddingProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taocan
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int uid { get; set; }
        public Nullable<int> HoID { get; set; }
        public Nullable<int> ChangID { get; set; }
        public Nullable<int> siyi { get; set; }
        public Nullable<int> sheying { get; set; }
        public Nullable<int> shexian { get; set; }
        public Nullable<int> huazhuang { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<bool> puty { get; set; }
        public Nullable<System.DateTime> datame { get; set; }
        public Nullable<System.DateTime> jiHua { get; set; }
        public string addr { get; set; }
    
        public virtual Changdi Changdi { get; set; }
        public virtual Hote Hote { get; set; }
        public virtual UserTB UserTB { get; set; }
        public virtual Yuan HuaZhu { get; set; }
        public virtual Yuan SX { get; set; }
        public virtual Yuan SY { get; set; }
        public virtual Yuan Siyi { get; set; }
    }
}
